// Generated by scripts/generate-clipboard-protocol.mjs. Do not edit.
export const ClipboardProtocol = {
    defaults: {
        maxUploadBytes: 26214400,
        ttlSeconds: 86400,
        maxChunkBytes: 262144,
    },
    commands: {
        OUTPUT: '0',
        SET_WINDOW_TITLE: '1',
        SET_PREFERENCES: '2',
        CLIPBOARD_UPLOAD_READY: '3',
        CLIPBOARD_UPLOAD_RESULT: '4',
        CLIPBOARD_UPLOAD_ERROR: '5',
        INPUT: '0',
        RESIZE_TERMINAL: '1',
        PAUSE: '2',
        RESUME: '3',
        CLIPBOARD_UPLOAD_START: '4',
        CLIPBOARD_UPLOAD_CHUNK: '5',
        CLIPBOARD_UPLOAD_FINISH: '6',
        CLIPBOARD_UPLOAD_ABORT: '7',
    },
    supportedImageTypes: ['image/png', 'image/jpeg', 'image/webp', 'image/gif'],
} as const;
