/* Generated by scripts/generate-clipboard-protocol.mjs. Do not edit. */
#include "clipboard_protocol.generated.h"

static const uint8_t clipboard_magic_0_0_0_bytes[] = {0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a};

static const clipboard_magic_part_t clipboard_magic_0_0_parts[] = {
  {0U, clipboard_magic_0_0_0_bytes, sizeof(clipboard_magic_0_0_0_bytes)}
};

static const clipboard_signature_variant_t clipboard_magic_0_variants[] = {
  {clipboard_magic_0_0_parts, sizeof(clipboard_magic_0_0_parts) / sizeof(clipboard_magic_0_0_parts[0])}
};

static const uint8_t clipboard_magic_1_0_0_bytes[] = {0xff, 0xd8, 0xff};

static const clipboard_magic_part_t clipboard_magic_1_0_parts[] = {
  {0U, clipboard_magic_1_0_0_bytes, sizeof(clipboard_magic_1_0_0_bytes)}
};

static const clipboard_signature_variant_t clipboard_magic_1_variants[] = {
  {clipboard_magic_1_0_parts, sizeof(clipboard_magic_1_0_parts) / sizeof(clipboard_magic_1_0_parts[0])}
};

static const uint8_t clipboard_magic_2_0_0_bytes[] = {0x52, 0x49, 0x46, 0x46};

static const uint8_t clipboard_magic_2_0_1_bytes[] = {0x57, 0x45, 0x42, 0x50};

static const clipboard_magic_part_t clipboard_magic_2_0_parts[] = {
  {0U, clipboard_magic_2_0_0_bytes, sizeof(clipboard_magic_2_0_0_bytes)},
  {8U, clipboard_magic_2_0_1_bytes, sizeof(clipboard_magic_2_0_1_bytes)}
};

static const clipboard_signature_variant_t clipboard_magic_2_variants[] = {
  {clipboard_magic_2_0_parts, sizeof(clipboard_magic_2_0_parts) / sizeof(clipboard_magic_2_0_parts[0])}
};

static const uint8_t clipboard_magic_3_0_0_bytes[] = {0x47, 0x49, 0x46, 0x38, 0x37, 0x61};

static const clipboard_magic_part_t clipboard_magic_3_0_parts[] = {
  {0U, clipboard_magic_3_0_0_bytes, sizeof(clipboard_magic_3_0_0_bytes)}
};

static const uint8_t clipboard_magic_3_1_0_bytes[] = {0x47, 0x49, 0x46, 0x38, 0x39, 0x61};

static const clipboard_magic_part_t clipboard_magic_3_1_parts[] = {
  {0U, clipboard_magic_3_1_0_bytes, sizeof(clipboard_magic_3_1_0_bytes)}
};

static const clipboard_signature_variant_t clipboard_magic_3_variants[] = {
  {clipboard_magic_3_0_parts, sizeof(clipboard_magic_3_0_parts) / sizeof(clipboard_magic_3_0_parts[0])},
  {clipboard_magic_3_1_parts, sizeof(clipboard_magic_3_1_parts) / sizeof(clipboard_magic_3_1_parts[0])}
};

const clipboard_image_type_t clipboard_image_types[] = {
  {"image/png", "png", clipboard_magic_0_variants, sizeof(clipboard_magic_0_variants) / sizeof(clipboard_magic_0_variants[0])},
  {"image/jpeg", "jpg", clipboard_magic_1_variants, sizeof(clipboard_magic_1_variants) / sizeof(clipboard_magic_1_variants[0])},
  {"image/webp", "webp", clipboard_magic_2_variants, sizeof(clipboard_magic_2_variants) / sizeof(clipboard_magic_2_variants[0])},
  {"image/gif", "gif", clipboard_magic_3_variants, sizeof(clipboard_magic_3_variants) / sizeof(clipboard_magic_3_variants[0])}
};

const size_t clipboard_image_type_count = sizeof(clipboard_image_types) / sizeof(clipboard_image_types[0]);
