/* Generated by scripts/generate-clipboard-protocol.mjs. Do not edit. */
#ifndef TTYD_CLIPBOARD_PROTOCOL_GENERATED_H
#define TTYD_CLIPBOARD_PROTOCOL_GENERATED_H

#include <stddef.h>
#include <stdint.h>

#define CLIPBOARD_UPLOAD_DEFAULT_MAX_SIZE 26214400U
#define CLIPBOARD_UPLOAD_DEFAULT_TTL 86400
#define CLIPBOARD_UPLOAD_MAX_CHUNK_SIZE 262144U
#define CLIPBOARD_UPLOAD_SIGNATURE_SIZE 12U
#define CLIPBOARD_UPLOAD_MIME_MAX 11U

#define OUTPUT '0'
#define SET_WINDOW_TITLE '1'
#define SET_PREFERENCES '2'
#define CLIPBOARD_UPLOAD_READY '3'
#define CLIPBOARD_UPLOAD_RESULT '4'
#define CLIPBOARD_UPLOAD_ERROR '5'
#define INPUT '0'
#define RESIZE_TERMINAL '1'
#define PAUSE '2'
#define RESUME '3'
#define CLIPBOARD_UPLOAD_START '4'
#define CLIPBOARD_UPLOAD_CHUNK '5'
#define CLIPBOARD_UPLOAD_FINISH '6'
#define CLIPBOARD_UPLOAD_ABORT '7'

typedef struct {
  size_t offset;
  const uint8_t *bytes;
  size_t length;
} clipboard_magic_part_t;

typedef struct {
  const clipboard_magic_part_t *parts;
  size_t part_count;
} clipboard_signature_variant_t;

typedef struct {
  const char *mime;
  const char *extension;
  const clipboard_signature_variant_t *variants;
  size_t variant_count;
} clipboard_image_type_t;

extern const clipboard_image_type_t clipboard_image_types[];
extern const size_t clipboard_image_type_count;

#endif
